/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/v1/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Service health
		 * @description Reports process liveness, whether the generator is loaded, whether a GPU is available, the arq queue depth, and the service version. Always 200 — degraded components are reported in the body, not as an HTTP error.
		 */
		get: operations['health_v1_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/generate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Queue a generation job
		 * @description Accepts a `GenerationSpec` and queues it for a worker. Returns 202 with a poll URL: generation is asynchronous, so no audio exists yet. Poll `GET /v1/jobs/{job_id}` for the result.
		 *
		 *     Every hard constraint in the spec is enforced during rendering and verified afterwards; a job that could not meet one finishes as `complete_with_warnings` rather than failing.
		 */
		post: operations['submit_generation_v1_generate_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/jobs/{job_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Poll a generation job
		 * @description Returns the job's current status. While `queued` or `processing` the `files` list is empty. On `complete` or `complete_with_warnings` it carries every rendered variant's URL plus `constraints_met`, the per-constraint pass/fail map.
		 */
		get: operations['get_job_v1_jobs__job_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/jobs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List recent jobs
		 * @description Newest first, paginated, optionally filtered by status. Each item carries the echoed spec, the constraint verdict, and file URLs for finished jobs — everything a dashboard or library needs to render a job without a second request per row. `limit` is capped at 100.
		 */
		get: operations['list_jobs_v1_jobs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/files/{job_id}/{variant}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Fetch a rendered sample
		 * @description Serves one variant of a finished job. Local-storage results are read from disk with the correct audio content type; remote (S3) results are answered with a 307 redirect to their object URL. Unauthenticated: browser audio elements cannot send the API key header, and the job id is a 128-bit random value.
		 */
		get: operations['get_file_v1_files__job_id___variant__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/batch': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Queue a batch of generation jobs
		 * @description Queues one job per spec, all sharing a `batch_id`. Specs are validated individually, so one bad spec rejects the whole request with 422 rather than half-queueing a batch.
		 *
		 *     `options.max_concurrent` and `options.on_failure` are recorded on the batch and applied by the worker as it drains the group; the API does not throttle enqueueing itself.
		 *
		 *     Rate limited to 10/minute per API key.
		 */
		post: operations['submit_batch_v1_batch_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/batches/{batch_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Poll a batch's progress
		 * @description Aggregate state of every job in the batch: how many finished, how many failed, and the per-job results for those that finished. Safe to poll repeatedly; each call recomputes from the database.
		 */
		get: operations['get_batch_v1_batches__batch_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/batches': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List batches
		 * @description Newest first, paginated, with per-batch completion counts. The counts are derived from the member jobs in a single grouped query, so they have the same never-stale guarantee as a poll. `limit` is capped at 100.
		 */
		get: operations['list_batches_v1_batches_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/recipes': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List recipes
		 * @description Newest first, paginated. `limit` is capped at 100 so a single request cannot pull the whole table.
		 */
		get: operations['list_recipes_v1_recipes_get'];
		put?: never;
		/**
		 * Save a recipe
		 * @description Stores a `GenerationSpec` under a unique name. The spec is validated on the way in, so a recipe can never be saved in a state the generator would reject.
		 */
		post: operations['create_recipe_v1_recipes_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/recipes/{recipe_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Fetch a recipe
		 * @description Return one saved recipe.
		 *
		 *     Args:
		 *         request: Incoming request.
		 *         recipe_id: The recipe to fetch.
		 *         session: Async database session.
		 *
		 *     Returns:
		 *         The recipe.
		 *
		 *     Raises:
		 *         HTTPException: 404 if it does not exist.
		 */
		get: operations['get_recipe_v1_recipes__recipe_id__get'];
		/**
		 * Update a recipe
		 * @description Partial update: send only the fields to change. Renaming to an existing name is a 409 rather than a silent overwrite.
		 */
		put: operations['update_recipe_v1_recipes__recipe_id__put'];
		post?: never;
		/**
		 * Delete a recipe
		 * @description Removes the recipe. Jobs already generated from it are untouched — the spec is denormalised onto each job row, so history stays reproducible.
		 */
		delete: operations['delete_recipe_v1_recipes__recipe_id__delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/recipes/{recipe_id}/run': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Generate from a saved recipe
		 * @description Queues a job using the recipe's stored spec. The job records the recipe it came from, so generated files can be traced back to the exact spec that produced them.
		 */
		post: operations['run_recipe_v1_recipes__recipe_id__run_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * BatchList
		 * @description A page of batches.
		 */
		BatchList: {
			/**
			 * Items
			 * @description Batches in this page, newest first.
			 */
			items?: components['schemas']['BatchListItem'][];
			/**
			 * Total
			 * @description Total batches matching the query.
			 */
			total: number;
			/**
			 * Limit
			 * @description Page size applied.
			 */
			limit: number;
			/**
			 * Offset
			 * @description Offset applied.
			 */
			offset: number;
		};
		/**
		 * BatchListItem
		 * @description One batch as it appears in the batch list.
		 *
		 *     Carries the same derived counts as :class:`BatchProgressResponse` but not
		 *     the per-job results — a list of N batches must not ship N full result sets.
		 */
		BatchListItem: {
			/**
			 * Batch Id
			 * @description Identifier shared by every job in the batch.
			 */
			batch_id: string;
			/**
			 * Completed
			 * @description Jobs that finished, with or without warnings.
			 */
			completed: number;
			/**
			 * Failed
			 * @description Jobs that failed.
			 */
			failed: number;
			/**
			 * Total
			 * @description Jobs in the batch.
			 */
			total: number;
			/**
			 * Created At
			 * Format: date-time
			 * @description When the batch was submitted.
			 */
			created_at: string;
		};
		/**
		 * BatchOptions
		 * @description How a multi-job batch should be executed.
		 *
		 *     Attributes:
		 *         parallel: Enqueue every job immediately rather than one at a time.
		 *         max_concurrent: Ceiling on jobs running at once. The worker applies it;
		 *             the API passes it through, so submitting a batch of 50 with
		 *             ``max_concurrent=4`` costs the same as submitting 4.
		 *         on_failure: ``"stop"`` cancels the remaining jobs when one fails;
		 *             ``"continue"`` lets the batch finish so partial results are usable.
		 */
		BatchOptions: {
			/**
			 * Parallel
			 * @description Enqueue all jobs immediately.
			 * @default true
			 */
			parallel: boolean;
			/**
			 * Max Concurrent
			 * @description Maximum jobs the worker should run at once.
			 * @default 4
			 */
			max_concurrent: number;
			/**
			 * On Failure
			 * @description What to do with the rest of the batch when a job fails.
			 * @default continue
			 * @enum {string}
			 */
			on_failure: 'stop' | 'continue';
		};
		/**
		 * BatchProgressResponse
		 * @description Aggregate state of a batch, recomputed from its jobs on every poll.
		 *
		 *     Counts are derived, never incremented in place: a poll always reflects the
		 *     database, so a worker crash cannot leave a batch permanently reporting 3 of
		 *     4 when the truth is unknowable.
		 */
		BatchProgressResponse: {
			/**
			 * Batch Id
			 * @description The batch being polled.
			 */
			batch_id: string;
			/**
			 * Completed
			 * @description Jobs that finished, with or without warnings.
			 */
			completed: number;
			/**
			 * Failed
			 * @description Jobs that failed.
			 */
			failed: number;
			/**
			 * Total
			 * @description Jobs in the batch.
			 */
			total: number;
			/**
			 * Results
			 * @description Per-job results, in submission order.
			 */
			results?: components['schemas']['GenerationResponse'][];
		};
		/**
		 * BatchRequest
		 * @description A batch of independent generation jobs submitted together.
		 */
		BatchRequest: {
			/**
			 * Specs
			 * @description One spec per job. Each is queued as its own job.
			 */
			specs: components['schemas']['GenerationSpec'][];
			/** @description Batch execution options. */
			options?: components['schemas']['BatchOptions'];
		};
		/**
		 * BatchSubmitResponse
		 * @description Acknowledgement returned when a batch is accepted.
		 */
		BatchSubmitResponse: {
			/**
			 * Batch Id
			 * @description Identifier shared by every job in the batch.
			 */
			batch_id: string;
			/**
			 * Total Jobs
			 * @description How many jobs were created.
			 */
			total_jobs: number;
			/**
			 * Poll Url
			 * @description Path to poll for the batch's progress.
			 */
			poll_url: string;
		};
		/**
		 * GeneratedFile
		 * @description A single rendered variant produced by a generation job.
		 *
		 *     Only :attr:`url` is guaranteed: a job row records where each variant landed,
		 *     and the measurements are filled in when the analysis pass runs over the
		 *     stored file. They are optional rather than zeroed so a consumer can tell
		 *     "not measured" from "measured as zero" — a peak of 0 dBFS is a clipped
		 *     master, not a missing value.
		 */
		GeneratedFile: {
			/**
			 * Url
			 * @description Download URL for the rendered file (typically a signed URL).
			 */
			url: string;
			/**
			 * Duration Ms
			 * @description Measured length of the rendered file, when analysed.
			 */
			duration_ms?: number | null;
			/**
			 * Peak Db
			 * @description Measured peak level in dBFS, when analysed.
			 */
			peak_db?: number | null;
			/** @description Post-generation spectral and temporal measurements, when analysed. */
			spectral_analysis?: components['schemas']['SpectralAnalysis'] | null;
		};
		/**
		 * GenerationResponse
		 * @description Result of a generation job, returned by the API and the worker.
		 *
		 *     One entry is present in :attr:`files` per generated variant, so
		 *     ``len(files)`` should equal the spec's ``batch_size`` on success.
		 */
		GenerationResponse: {
			/**
			 * Job Id
			 * @description Identifier of the generation job.
			 */
			job_id: string;
			/**
			 * Status
			 * @description Current or final job status.
			 * @enum {string}
			 */
			status: 'queued' | 'processing' | 'complete' | 'complete_with_warnings' | 'failed';
			/**
			 * Files
			 * @description Rendered variants, one per successful sample in the batch.
			 */
			files?: components['schemas']['GeneratedFile'][];
			/**
			 * Constraints Met
			 * @description Per-constraint pass/fail map, keyed by constraint name (e.g. {'fundamental_hz': true, 'spectral_ceiling_hz': true}). Built by GenerationSpec.evaluate_constraints, so when a job completes normally it carries a verdict on every hard constraint.
			 */
			constraints_met?: {
				[key: string]: boolean;
			};
			/** @description The spec this job was submitted with, echoed back so a client can rebuild overlays and reports without having kept its own copy. None only when the stored spec no longer validates. */
			spec?: components['schemas']['GenerationSpec'] | null;
		};
		/**
		 * GenerationSpec
		 * @description A machine-readable specification of a single audio sample.
		 *
		 *     A spec is the only input the generation pipeline needs. It answers four
		 *     questions:
		 *
		 *     1. **What kind of sound?** — :attr:`type`, :attr:`category`.
		 *     2. **How long and in what format?** — :attr:`duration_ms` /
		 *        :attr:`duration_beats`, :attr:`sample_rate`, :attr:`bit_depth`,
		 *        :attr:`channels`, :attr:`format`, :attr:`metadata_embed`.
		 *     3. **What must the signal obey?** — the *hard* constraints
		 *        (:attr:`fundamental_hz`, :attr:`spectral_floor_hz`,
		 *        :attr:`spectral_ceiling_hz`, :attr:`spectral_tilt_db_per_octave`,
		 *        :attr:`peak_db`, and the ADSR envelope in :attr:`attack_ms`,
		 *        :attr:`decay_ms`, :attr:`sustain_level`, :attr:`release_ms`).
		 *        These are enforced by DSP post-processing and then re-measured; the
		 *        result is reported back in :class:`SpectralAnalysis` and judged by
		 *        :meth:`evaluate_constraints` against :attr:`tolerances`.
		 *     4. **What musical context should bias the model?** — the *soft* context
		 *        (:attr:`bpm`, :attr:`key`, :attr:`genre`, :attr:`mood`,
		 *        :attr:`reference_sample_url`). The model is conditioned on these, but
		 *        they are never guaranteed: a loop tagged ``128 BPM`` may contain
		 *        microtiming that a human then straightens out.
		 *
		 *     The distinction matters when reading generation results: a hard constraint
		 *     that was missed is a bug in the post-processing chain, while a soft hint
		 *     that was ignored is not.
		 *
		 *     **Duration handling.** Time-based samples (:attr:`type` other than
		 *     ``"loop"``) are measured in milliseconds via :attr:`duration_ms`.
		 *     Loops are measured in beats via :attr:`duration_beats` and additionally
		 *     require :attr:`bpm`, which lets the validator derive the loop's real
		 *     duration (``beats * 60000 / bpm``) so the envelope and duration
		 *     constraints can be checked for loops as well.
		 *
		 *     **Cross-field validation** (performed in a single ``model_validator``):
		 *
		 *     * ``type="loop"`` requires :attr:`duration_beats` and :attr:`bpm`; every
		 *       other type requires :attr:`duration_ms`.
		 *     * :attr:`fundamental_hz` must be an ascending, positive range.
		 *     * The fundamental must sit strictly *inside* the usable band:
		 *       ``spectral_floor_hz < fundamental_min <= fundamental_max <
		 *       spectral_ceiling_hz``. A fundamental outside the band would be removed
		 *       by its own high-pass/low-pass, making the spec self-contradictory.
		 *     * ``attack_ms + decay_ms + release_ms < duration_ms`` — the envelope has to
		 *       fit inside the sample with room to spare.
		 *
		 *     Examples:
		 *         >>> spec = GenerationSpec(
		 *         ...     type="one_shot",
		 *         ...     category="kick",
		 *         ...     duration_ms=800,
		 *         ...     fundamental_hz=(40.0, 90.0),
		 *         ...     spectral_floor_hz=25.0,
		 *         ...     spectral_ceiling_hz=12000.0,
		 *         ...     peak_db=-12.0,
		 *         ...     attack_ms=1.0,
		 *         ...     decay_ms=400.0,
		 *         ...     sustain_level=0.0,
		 *         ...     release_ms=50.0,
		 *         ...     bpm=140.0,
		 *         ...     key="F#m",
		 *         ...     genre="techno",
		 *         ... )
		 *         >>> spec.duration_ms
		 *         800
		 * @example {
		 *       "attack_ms": 1,
		 *       "batch_size": 4,
		 *       "bit_depth": 24,
		 *       "bpm": 140,
		 *       "category": "kick",
		 *       "channels": 2,
		 *       "decay_ms": 400,
		 *       "diversity": 0.7,
		 *       "duration_ms": 800,
		 *       "format": "wav",
		 *       "fundamental_hz": [
		 *         40,
		 *         90
		 *       ],
		 *       "genre": "techno",
		 *       "key": "F#m",
		 *       "metadata_embed": true,
		 *       "mood": "dark",
		 *       "peak_db": -12,
		 *       "release_ms": 50,
		 *       "sample_rate": 44100,
		 *       "spectral_ceiling_hz": 12000,
		 *       "spectral_floor_hz": 25,
		 *       "spectral_tilt_db_per_octave": -3,
		 *       "sustain_level": 0,
		 *       "type": "one_shot"
		 *     }
		 */
		GenerationSpec: {
			/**
			 * Type
			 * @description Sound archetype. 'one_shot' is a single hit (kick, snare), 'loop' is a beat-aligned loop, 'texture' is an evolving bed or drone, and 'stinger' is a short dramatic transition.
			 * @enum {string}
			 */
			type: 'one_shot' | 'loop' | 'texture' | 'stinger';
			/**
			 * Category
			 * @description Instrument/role slug, e.g. 'kick', 'snare', 'hihat', 'riser', 'impact', 'pad'.
			 * @example kick
			 */
			category: string;
			/**
			 * Duration Ms
			 * @description Length in milliseconds. Required for every type except 'loop'. For loops this field is derived from duration_beats and bpm.
			 */
			duration_ms?: number | null;
			/**
			 * Duration Beats
			 * @description Length in beats (e.g. 2.0 for a one-bar loop at 4/4). Required when type='loop'; ignored otherwise.
			 */
			duration_beats?: number | null;
			/**
			 * Sample Rate
			 * @description Sample rate in Hz.
			 * @default 44100
			 */
			sample_rate: number;
			/**
			 * Bit Depth
			 * @description Bit depth of the written file.
			 * @default 24
			 */
			bit_depth: number;
			/**
			 * Channels
			 * @description 1 = mono, 2 = stereo.
			 * @default 2
			 */
			channels: number;
			/**
			 * Fundamental Hz
			 * @description Permitted range for the fundamental frequency as (min_hz, max_hz). Hard constraint: the generated fundamental is pitch-shifted into this window.
			 * @example [
			 *       40,
			 *       90
			 *     ]
			 */
			fundamental_hz: [number, number];
			/**
			 * Spectral Ceiling Hz
			 * @description Low-pass corner in Hz. All energy above this frequency is rolled off (hard constraint).
			 */
			spectral_ceiling_hz: number;
			/**
			 * Spectral Floor Hz
			 * @description High-pass corner in Hz. All energy below this frequency is removed (hard constraint). Must stay below fundamental_hz[0].
			 */
			spectral_floor_hz: number;
			/**
			 * Spectral Tilt Db Per Octave
			 * @description Spectral tilt applied per octave above the fundamental. Negative values darken the sample, positive values brighten it. 0.0 leaves the natural balance untouched.
			 * @default 0
			 */
			spectral_tilt_db_per_octave: number;
			/**
			 * Peak Db
			 * @description Target peak level in dBFS (e.g. -12.0). The output is normalised to this value; it must not exceed 0 dBFS to avoid clipping.
			 */
			peak_db: number;
			/**
			 * Attack Ms
			 * @description Attack time in milliseconds.
			 */
			attack_ms: number;
			/**
			 * Decay Ms
			 * @description Decay time in milliseconds.
			 */
			decay_ms: number;
			/**
			 * Sustain Level
			 * @description Sustain amplitude as a 0-1 fraction of the peak level.
			 */
			sustain_level: number;
			/**
			 * Release Ms
			 * @description Release time in milliseconds.
			 */
			release_ms: number;
			/**
			 * Bpm
			 * @description Tempo in BPM. Soft conditioning — except for loops, where it also defines the sample's real duration.
			 */
			bpm: number;
			/**
			 * Key
			 * @description Musical key, e.g. 'F#m', 'C major', 'A min'.
			 */
			key: string;
			/**
			 * Genre
			 * @description Target genre, e.g. 'techno', 'house', 'cinematic'.
			 */
			genre: string;
			/**
			 * Mood
			 * @description Optional mood descriptor, e.g. 'dark', 'aggressive', 'ethereal'.
			 */
			mood?: string | null;
			/**
			 * Reference Sample Url
			 * @description Optional URL of a reference sample ('make something like this'). Soft conditioning only — the model never copies the reference.
			 */
			reference_sample_url?: string | null;
			/**
			 * Batch Size
			 * @description Number of variants to generate for this spec.
			 * @default 1
			 */
			batch_size: number;
			/**
			 * Diversity
			 * @description Variation between batch items: 0.0 = identical, 1.0 = maximum variation.
			 * @default 0.5
			 */
			diversity: number;
			/**
			 * Format
			 * @description Container/codec of the delivered file.
			 * @default wav
			 * @enum {string}
			 */
			format: 'wav' | 'flac' | 'mp3';
			/**
			 * Metadata Embed
			 * @description Embed licence and generation parameters in the file metadata (ID3v2 for mp3, VBRI for flac, LIST/INFO for wav).
			 * @default true
			 */
			metadata_embed: boolean;
			/**
			 * Stereo Width
			 * @description Target side/mid level ratio, enforced with M/S processing. 0.0 collapses the sample to mono, 1.0 gives an equal side and mid level, higher values exaggerate the stereo image. None leaves the model's own width untouched.
			 */
			stereo_width?: number | null;
			/** @description Slack applied when checking the rendered output against this spec's hard constraints. See :meth:`evaluate_constraints`. */
			tolerances?: components['schemas']['Tolerances'];
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/**
		 * HealthResponse
		 * @description Service health, as reported by ``GET /v1/health``.
		 *
		 *     ``status`` is ``"ok"`` or ``"degraded"``. The HTTP status stays 200 either
		 *     way: a 503 would take the instance out of a load balancer's rotation, which
		 *     is the opposite of what an operator wants when one optional component is
		 *     unhappy.
		 */
		HealthResponse: {
			/**
			 * Status
			 * @description 'degraded' when a dependency is unavailable.
			 * @enum {string}
			 */
			status: 'ok' | 'degraded';
			/**
			 * Model Loaded
			 * @description Whether this process already holds a loaded generator.
			 */
			model_loaded: boolean;
			/**
			 * Gpu Available
			 * @description Whether a CUDA device is usable.
			 */
			gpu_available: boolean;
			/**
			 * Queue Depth
			 * @description Jobs waiting in the arq queue, or null when the broker could not be reached. Null, not 0: an unreachable broker and an empty queue are different situations.
			 */
			queue_depth?: number | null;
			/**
			 * Version
			 * @description Service version.
			 */
			version: string;
			/**
			 * Detail
			 * @description Why the service is degraded, when it is.
			 */
			detail?: string | null;
		};
		/**
		 * JobList
		 * @description A page of recent jobs.
		 */
		JobList: {
			/**
			 * Items
			 * @description Jobs in this page, newest first.
			 */
			items?: components['schemas']['JobListItem'][];
			/**
			 * Total
			 * @description Total jobs matching the query.
			 */
			total: number;
			/**
			 * Limit
			 * @description Page size applied.
			 */
			limit: number;
			/**
			 * Offset
			 * @description Offset applied.
			 */
			offset: number;
		};
		/**
		 * JobListItem
		 * @description One job as it appears in the recent-jobs list.
		 *
		 *     A superset of :class:`GenerationResponse`: everything a job poll returns,
		 *     plus the row metadata a list needs (ownership by a batch or recipe, and
		 *     when the job was created and last touched).
		 */
		JobListItem: {
			/**
			 * Job Id
			 * @description Identifier of the generation job.
			 */
			job_id: string;
			/**
			 * Status
			 * @description Current or final job status.
			 * @enum {string}
			 */
			status: 'queued' | 'processing' | 'complete' | 'complete_with_warnings' | 'failed';
			/**
			 * Files
			 * @description Rendered variants, one per successful sample in the batch.
			 */
			files?: components['schemas']['GeneratedFile'][];
			/**
			 * Constraints Met
			 * @description Per-constraint pass/fail map, keyed by constraint name (e.g. {'fundamental_hz': true, 'spectral_ceiling_hz': true}). Built by GenerationSpec.evaluate_constraints, so when a job completes normally it carries a verdict on every hard constraint.
			 */
			constraints_met?: {
				[key: string]: boolean;
			};
			/** @description The spec this job was submitted with, echoed back so a client can rebuild overlays and reports without having kept its own copy. None only when the stored spec no longer validates. */
			spec?: components['schemas']['GenerationSpec'] | null;
			/**
			 * Batch Id
			 * @description Batch this job belongs to, if any.
			 */
			batch_id?: string | null;
			/**
			 * Recipe Id
			 * @description Recipe this job was launched from, if any.
			 */
			recipe_id?: string | null;
			/**
			 * Created At
			 * Format: date-time
			 * @description When the job was submitted.
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 * @description When the job last changed state.
			 */
			updated_at: string;
		};
		/**
		 * JobSubmitResponse
		 * @description Acknowledgement returned when a job is accepted.
		 *
		 *     Carries the poll URL rather than making the client construct it, so the
		 *     path shape lives in one place.
		 */
		JobSubmitResponse: {
			/**
			 * Job Id
			 * @description Identifier of the queued job.
			 */
			job_id: string;
			/**
			 * Status
			 * @description Job status at submission time.
			 * @enum {string}
			 */
			status: 'queued' | 'processing' | 'complete' | 'complete_with_warnings' | 'failed';
			/**
			 * Poll Url
			 * @description Path to poll for the job's result.
			 */
			poll_url: string;
		};
		/**
		 * RecipeCreate
		 * @description A named, reusable spec saved for later.
		 */
		RecipeCreate: {
			/**
			 * Name
			 * @description Unique recipe name.
			 */
			name: string;
			/**
			 * Description
			 * @description What this recipe is for.
			 */
			description?: string | null;
			/** @description The spec to save. */
			spec: components['schemas']['GenerationSpec'];
		};
		/**
		 * RecipeList
		 * @description A page of recipes.
		 */
		RecipeList: {
			/**
			 * Items
			 * @description Recipes in this page, newest first.
			 */
			items?: components['schemas']['RecipeRead'][];
			/**
			 * Total
			 * @description Total recipes matching the query.
			 */
			total: number;
			/**
			 * Limit
			 * @description Page size applied.
			 */
			limit: number;
			/**
			 * Offset
			 * @description Offset applied.
			 */
			offset: number;
		};
		/**
		 * RecipeRead
		 * @description A saved recipe as returned by the API.
		 */
		RecipeRead: {
			/**
			 * Id
			 * @description Recipe identifier.
			 */
			id: string;
			/**
			 * Name
			 * @description Unique recipe name.
			 */
			name: string;
			/**
			 * Description
			 * @description What it is for.
			 */
			description?: string | null;
			/** @description The stored spec. */
			spec: components['schemas']['GenerationSpec'];
			/**
			 * Created At
			 * Format: date-time
			 * @description When the recipe was saved.
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 * @description When the recipe was last modified.
			 */
			updated_at: string;
		};
		/**
		 * RecipeRunResponse
		 * @description Acknowledgement for a job launched from a saved recipe.
		 */
		RecipeRunResponse: {
			/**
			 * Job Id
			 * @description Identifier of the queued job.
			 */
			job_id: string;
			/**
			 * Status
			 * @description Job status at submission time.
			 * @enum {string}
			 */
			status: 'queued' | 'processing' | 'complete' | 'complete_with_warnings' | 'failed';
			/**
			 * Poll Url
			 * @description Path to poll for the job's result.
			 */
			poll_url: string;
		};
		/**
		 * RecipeUpdate
		 * @description Partial update of a saved recipe.
		 *
		 *     Every field is optional, so a caller can rename a recipe without resending
		 *     the spec, or edit the spec without touching the name.
		 */
		RecipeUpdate: {
			/**
			 * Name
			 * @description New name.
			 */
			name?: string | null;
			/**
			 * Description
			 * @description New description.
			 */
			description?: string | null;
			/** @description New spec. */
			spec?: components['schemas']['GenerationSpec'] | null;
		};
		/**
		 * SpectralAnalysis
		 * @description Measurements taken from a generated file *after* post-processing.
		 *
		 *     These are the empirical values, not the requested ones. Comparing them
		 *     against the originating :class:`GenerationSpec` tells you whether the hard
		 *     constraints were actually honoured.
		 *
		 *     The first three fields come from point measurements (a pitch estimate, a
		 *     band energy ratio, an envelope segmentation). :attr:`floor_slope_db_per_oct`
		 *     and :attr:`tilt_measured_db_per_octave` come from least-squares slope fits
		 *     over the spectrum, which is why they are reported as dB per octave rather
		 *     than absolute dB.
		 */
		SpectralAnalysis: {
			/**
			 * Fundamental Detected Hz
			 * @description Fundamental frequency measured in the output, in Hz.
			 */
			fundamental_detected_hz: number;
			/**
			 * Ceiling Violation Db
			 * @description Energy found above spectral_ceiling_hz, in dB relative to the ceiling. 0.0 or less means the roll-off held; positive values mean the ceiling was exceeded.
			 */
			ceiling_violation_db: number;
			/**
			 * Attack Measured Ms
			 * @description Attack time measured in the output, in milliseconds.
			 */
			attack_measured_ms: number;
			/**
			 * Floor Slope Db Per Oct
			 * @description Measured high-pass slope below spectral_floor_hz, in dB per octave. Negative values mean energy falls as frequency drops: -6 is a single-pole filter, -24 is a 4-pole one. Values >= 0 mean no usable high-pass was applied.
			 */
			floor_slope_db_per_oct: number;
			/**
			 * Tilt Measured Db Per Octave
			 * @description Measured spectral slope above the fundamental, in dB per octave. Compared against the spec's spectral_tilt_db_per_octave to confirm the requested darkening or brightening was actually applied.
			 */
			tilt_measured_db_per_octave: number;
		};
		/**
		 * Tolerances
		 * @description Per-constraint slack used when verifying a rendered sample.
		 *
		 *     DSP post-processing can only ever get *close* to a target: a filter's
		 *     roll-off is finite, a fade is sample-quantised, and a peak normaliser lands
		 *     on the nearest representable step. Without tolerances, every generated file
		 *     would report as a constraint violation over floating-point dust.
		 *
		 *     Tolerances turn the spec's exact targets into pass/fail bands for
		 *     :meth:`GenerationSpec.evaluate_constraints`. Defaults are tuned to be tight
		 *     enough to catch real failures (a wrong pitch, a missing low-pass, a clipped
		 *     master) while ignoring measurement noise. Loosen them when you want
		 *     "close enough to use", tighten them when you want a QC gate.
		 *
		 *     Slack tolerances are non-negative — a negative one would make the constraint
		 *     unsatisfiable. The two roll-off thresholds (:attr:`ceiling_violation_db` and
		 *     :attr:`floor_slope_db_per_oct`) are instead required to be non-positive,
		 *     because they bound how much energy may leak past a filter, not how far a
		 *     measurement may drift from its target.
		 */
		Tolerances: {
			/**
			 * Fundamental Hz
			 * @description Slack in Hz added to *both* edges of fundamental_hz when checking the detected fundamental. Raise it for wide-window windows (e.g. pads) where small pitch deviations are inaudible.
			 * @default 5
			 */
			fundamental_hz: number;
			/**
			 * Ceiling Violation Db
			 * @description Maximum tolerated stopband energy above spectral_ceiling_hz, in dB relative to the passband. The default -40 dB demands a clean roll-off; must be <= 0 (a positive value would defeat the constraint entirely).
			 * @default -40
			 */
			ceiling_violation_db: number;
			/**
			 * Floor Slope Db Per Oct
			 * @description Steepest high-pass roll-off accepted below spectral_floor_hz, in dB per octave. The default -12 dB/oct requires at least a 2-pole high-pass (-24 dB/oct would satisfy it comfortably); a shallower measurement means low-end energy is bleeding through.
			 * @default -12
			 */
			floor_slope_db_per_oct: number;
			/**
			 * Peak Db
			 * @description Absolute tolerance in dB around the target peak level.
			 * @default 0.5
			 */
			peak_db: number;
			/**
			 * Attack Ms
			 * @description Absolute tolerance in milliseconds on the measured attack.
			 * @default 2
			 */
			attack_ms: number;
			/**
			 * Tilt Db Per Octave
			 * @description Absolute tolerance in dB per octave on the measured spectral tilt versus spectral_tilt_db_per_octave. Slopes are fitted across many octaves, so this is naturally looser than the level tolerances.
			 * @default 1.5
			 */
			tilt_db_per_octave: number;
			/**
			 * Duration Pct
			 * @description Relative tolerance on total duration (0.02 = 2%). One rendered sample at 44.1 kHz is 2.3 ms, so the default already permits off-by-one rounding.
			 * @default 0.02
			 */
			duration_pct: number;
			/**
			 * Stereo Width
			 * @description Absolute tolerance on the measured side/mid ratio. M/S rescaling hits its target closely, so this is mostly a guard against the ratio being undefined on near-mono material.
			 * @default 0.05
			 */
			stereo_width: number;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	health_v1_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthResponse'];
				};
			};
		};
	};
	submit_generation_v1_generate_post: {
		parameters: {
			query?: never;
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['GenerationSpec'];
			};
		};
		responses: {
			/** @description Successful Response */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobSubmitResponse'];
				};
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The spec is invalid or violates a hard constraint. */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Rate limit exceeded. */
			429: {
				headers: {
					/** @description Seconds to wait. */
					'Retry-After'?: unknown;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The API is unconfigured, or the job queue is unreachable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_job_v1_jobs__job_id__get: {
		parameters: {
			query?: never;
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path: {
				job_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GenerationResponse'];
				};
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No such job. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_jobs_v1_jobs_get: {
		parameters: {
			query?: {
				/** @description Page size. */
				limit?: number;
				/** @description Jobs to skip. */
				offset?: number;
				/** @description Only return jobs in this state. */
				status?:
					('queued' | 'processing' | 'complete' | 'complete_with_warnings' | 'failed') | null;
			};
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobList'];
				};
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_file_v1_files__job_id___variant__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				job_id: string;
				/** @description Zero-based variant index within the job's result set. */
				variant: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description No such job, no such variant, or the file is gone. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	submit_batch_v1_batch_post: {
		parameters: {
			query?: never;
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['BatchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BatchSubmitResponse'];
				};
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description One or more specs are invalid. */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Rate limit exceeded. */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The API is unconfigured, or the job queue is unreachable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_batch_v1_batches__batch_id__get: {
		parameters: {
			query?: never;
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path: {
				batch_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BatchProgressResponse'];
				};
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No such batch. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_batches_v1_batches_get: {
		parameters: {
			query?: {
				/** @description Page size. */
				limit?: number;
				/** @description Batches to skip. */
				offset?: number;
			};
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['BatchList'];
				};
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_recipes_v1_recipes_get: {
		parameters: {
			query?: {
				/** @description Page size. */
				limit?: number;
				/** @description Recipes to skip. */
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RecipeList'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_recipe_v1_recipes_post: {
		parameters: {
			query?: never;
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RecipeCreate'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RecipeRead'];
				};
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description A recipe with that name exists. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The spec is invalid. */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_recipe_v1_recipes__recipe_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				recipe_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RecipeRead'];
				};
			};
			/** @description No such recipe. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	update_recipe_v1_recipes__recipe_id__put: {
		parameters: {
			query?: never;
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path: {
				recipe_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RecipeUpdate'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RecipeRead'];
				};
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No such recipe. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description That name is already taken. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	delete_recipe_v1_recipes__recipe_id__delete: {
		parameters: {
			query?: never;
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path: {
				recipe_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No such recipe. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	run_recipe_v1_recipes__recipe_id__run_post: {
		parameters: {
			query?: never;
			header?: {
				/** @description API key identifying the caller. */
				'X-API-Key'?: string | null;
			};
			path: {
				recipe_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RecipeRunResponse'];
				};
			};
			/** @description Missing or invalid API key. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No such recipe. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description The queue is unreachable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
