"""initial schema: generation_jobs, generation_batches, recipes

Revision ID: 0001_initial
Revises:
Create Date: 2026-10-08

Mirrors app/models/db.py exactly. Written by hand rather than autogenerated so
the JSON columns, timezone-aware timestamps, and index names are deliberate:

* JSON columns get no server_default. The defaults in the models (list/dict) are
  applied by the ORM on insert, and a Postgres ``'[]'::json`` server_default
  would not survive a SQLite round trip.
* created_at/updated_at use ``now()`` at the database level, so a row inserted
  outside the application (a migration, psql, a backfill script) still gets a
  timestamp. updated_at's application-side refresh is ORM behaviour and has no
  DDL equivalent.
* recipe name is unique at the database level, not just in the API: two workers
  racing to create "kick-01" must not both succeed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the three tables and their indexes."""
    op.create_table(
        "generation_batches",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("total_jobs", sa.Integer(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("base_seed", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.String(length=64), nullable=True),
        sa.Column("recipe_id", sa.String(length=64), nullable=True),
        sa.Column("result_urls", sa.JSON(), nullable=False),
        sa.Column("constraint_report", sa.JSON(), nullable=True),
        sa.Column("error", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Polling GET /v1/jobs/{id} filters on status in dashboards and admin views,
    # and every batch poll joins on batch_id.
    op.create_index("ix_generation_jobs_status", "generation_jobs", ["status"])
    op.create_index("ix_generation_jobs_batch_id", "generation_jobs", ["batch_id"])

    op.create_table(
        "recipes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_recipes_name", "recipes", ["name"], unique=True)


def downgrade() -> None:
    """Drop everything, children before parents.

    There are no foreign keys between these tables (batch_id and recipe_id are
    soft references, so deleting a batch never has to cascade), but the order
    still reads correctly.
    """
    op.drop_index("ix_recipes_name", table_name="recipes")
    op.drop_table("recipes")
    op.drop_index("ix_generation_jobs_batch_id", table_name="generation_jobs")
    op.drop_index("ix_generation_jobs_status", table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_table("generation_batches")
